import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body suppressHydrationWarning className="leading-normal tracking-normal text-indigo-400 sm:flex-col p-6 bg-cover bg-fixed flex h-full">
        
          {children}
      </body>
    </html>
  );
}
